### PR TITLE
fix example in README.md

### PR DESCRIPTION
**Pull request by kotarella1110**
The example in Readme.md that doesn't work!
Please merge this PR!

### CODE REVIEW

**Comment by bluebill1049** [comment]
Thank you 😊

**Comment by bluebill1049** [comment]
You want to update the readme and include itself as a contributor?

**Comment by kotarella1110** [comment]
Yes. I'm really glad about that!

**Comment by kotarella1110** [comment]
@bluebill1049 Thanks! 💚

**Comment by bluebill1049** [comment]
Thanks you too @kotarella1110

**Pull request merged**
